[package]
name = "proto"
version = "0.1.4"
edition = "2024"
build = "build.rs"

[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"
tonic = "0.14.1"
tonic-prost = "0.14.1"

[build-dependencies]
tonic-prost-build = "0.14.1"
