[package]
name = "proto"
version = "0.3.0"
edition = "2024"
build = "build.rs"

[dependencies]
prost = "0.14.2"
prost-types = "0.14.2"
tonic = "0.14.2"
tonic-prost = "0.14.2"

[build-dependencies]
tonic-prost-build = "0.14.2"
